[package]
name = "es5e_importer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_es5e_core = { path = "../lib_es5e_core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
